import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { isLoaded, isSignedIn, user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        {isSignedIn ? (
          <div className="flex flex-col items-center justify-center">
            <h1 className="text-4xl font-bold">Hello {user.fullName}!</h1>
            <p className="text-2xl font-medium">You are signed in.</p>
            <SignOutButton className="text-2xl font-medium underline">
              Sign out
            </SignOutButton>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center">
            <h1 className="text-4xl font-bold">Hello!</h1>
            <p className="text-2xl font-medium">You are not signed in.</p>
            <SignInButton className="text-2xl font-medium underline">
              Sign in
            </SignInButton>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
