import { useState } from "react";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

import { type RouterOutputs, api } from "~/utils/api";
import Image from "next/image";
import { LoadingPage, LoadingSpinner } from "~/components/Loading";
import toast from "react-hot-toast";

const SinglePostPage: NextPage = () => {
  const { isLoaded: userIsLoaded, isSignedIn, user } = useUser();
  api.posts.getAll.useQuery();

  if (!userIsLoaded) {
    return <div />;
  }

  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {isSignedIn ? (
          <div className="flex flex-col items-center justify-center">
            <h1 className="text-4xl font-bold">Hello {user.fullName}!</h1>
            <SignOutButton>Sign out</SignOutButton>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center">
            <h1 className="text-4xl font-bold">Hello!</h1>
            <p className="text-2xl font-medium">You are not signed in.</p>
            <SignInButton>Sign in</SignInButton>
          </div>
        )}
      </main>
    </>
  );
};

export default SinglePostPage;
